# Generated by Django 4.1.3 on 2022-11-28 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('side1', models.CharField(max_length=20)),
                ('side2', models.CharField(max_length=20)),
                ('coefficient', models.FloatField(default=1)),
                ('year', models.IntegerField(null=True)),
                ('day', models.IntegerField(null=True)),
                ('time', models.TimeField(null=True)),
            ],
            options={
                'db_table': 'match',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcut', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'sector',
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'stadium',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('count', models.IntegerField()),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App1.sector')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.stadium')),
            ],
            options={
                'db_table': 'place',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=20, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.match')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.place')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.stadium'),
        ),
    ]
