# Generated by Django 4.1.3 on 2022-11-28 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilesApp', '0002_remove_profile_orders'),
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.match')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.place')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
