# Generated by Django 4.1.3 on 2022-11-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_ticket_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='day',
        ),
        migrations.RemoveField(
            model_name='match',
            name='year',
        ),
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
